export const MESSAGE_PATTERNS = {
  USER_ACCOUNT_PROFILE: {
    AUTH: {
      SIGNUP: 'signup',
      VERIFY_EMAIL: 'verify_email',
      SIGNIN: 'signin',
      GET_USER_INFO: 'get_user_info',
      SIGNOUT: 'signout',
      CHANGE_PASSWORD: 'change_password',
      FORGOT_PASSWORD: 'forgot_password',
      CONFIRM_FORGOT_PASSWORD: 'confirm_forgot_password',
      RESEND_LINK: 'resend_link',
      UPDATE_USER_PASSWORD: 'update_user_password',
      GET_USER_EMAIL_TO_SET_PASSWORD: 'get_user_email_to_set_password',
      COMPANY_APPROVAL: 'company_approval',
      SET_NEW_PASSWORD: 'set_new_password',
      RESET_PASSWORD: 'reset_password',
    },
    TOKEN: {
      VERIFY_TOKEN: 'verify_token',
      REFRESH_TOKEN: 'refresh_token',
    },
    ADMIN_USER: {
      ADMIN_CREATE_USER: 'admin_create_user',
      ADMIN_RESEND_PASSWORD: 'admin_resend_password',
      ADMIN_LIST_USERS: 'admin_list_users',
      ADMIN_GET_USER: 'admin_get_user',
      ADMIN_UPDATE_USER: 'admin_update_user',
      ADMIN_DELETE_USER: 'admin_delete_user',
      ADMIN_USER_CHANGE_STATUS: 'admin_user_change_status',
      ADMIN_CONFIRM_SIGNUP: 'admin_confirm_signup',
      ADMIN_ASSIGN_ROLE: 'admin_assign_role',
      ADMIN_REMOVE_ROLE: 'admin_remove_role',
      ADMIN_GET_USER_COUNT: 'admin_get_user_count',
      ADMIN_GET_REMINDERS: 'admin_get_reminders',
      ADMIN_GET_RECENT_ACTIVITY: 'admin_get_recent_activity',
      ADMIN_CREATE_LOG: 'admin_create_auditLog',
      ADMIN_GET_ALL_LOG: 'admin_get_all_auditLog',
      ADMIN_GET_RECENT_AUDIT_TRAIL: 'admin_get_recent_audit_trail',
      ADMIN_SEARCH_USERS: 'admin_search_users',
      ADMIN_UPDATE_USER_EMAIL: 'admin_update_user_email',
      ADMIN_UPDATE_USER_PASSWORD: 'admin_update_user_password',
      CHANGE_STATUS_DELEGATE: 'change_status_delegate',
      ADMIN_ADD_REMINDER: 'admin_add_reminder',
      ADMIN_GET_REMINDER: 'admin_get_reminder',
      GET_TOTAL_COUNT: 'get_total_count',
      LIST_CONNECTED_DEVICES: 'list_connected_devices',
      GET_VERIFIED_PRODUCT_COUNT: 'get_verified_product_count',
      ADMIN_LIST_REMINDERS: 'admin_list_reminders',
    },
    USER: {
      LIST_ALL_USERS: 'list_all_users',
      LIST_USERS: 'list_users',
      GET_USER: 'get_user',
      GET_PROFILE_IMAGE: 'get_profile_image',
      CHANGE_USER_STATUS: 'change_user_status',
      CHECK_USER_EMAIL_OR_PHONE: 'check_user_email_or_phone',
      ADMIN_USER_CHANGE_STATUS: 'admin_user_change_status',
      CHECK_PHONE: 'check_phone',
      CHECK_EMAIL: 'check_email',
      REQUEST_VERIFICATION: 'request_verification',
      GET_USER_FOR_AUTH: 'get_user_for_auth',
      CREATE_USER_DB: 'create_user',
      GET_USER_ESSENTIALS: 'get_user_essentials',
      CREATE_USER: 'create_user',
      ALL_EMPLOYEES: 'all-employees',
      UPDATE_USER: 'update_user',
      UPDATE_USER_MANY: 'update_user_many',
      DELETE_USER: 'delete_user',
      UPDATE_PROFILE_IMAGE: 'update_profile_image',
      REMOVE_PROFILE_IMAGE: 'remove_user_profile',
      IG_VERIFICATION: 'ig_verification',
      VERIFICATION_UPDATE: 'verification_update',
    },
  },
  NOTIFICATIONS: {
    ALL_NOTIFICATIONS: 'get_all_notifications',
    SINGLE_NOTIFICATION: 'get_notification',
    DELETE_NOTIFICATION: 'delete_notification',
    DELETE_ALL_NOTIFICATIONS: 'delete_all_notifications',
    READ_SINGLE_NOTIFICATION: 'read_single_notification',
    READ_ALL_NOTIFICATIONS: 'read_all_notifications',
    LATEST_NOTIFICATIONS: 'get_latest_notifications',
    UNREAD_NOTIFICATIONS: 'unread_notification',
    UNREAD_ALL_NOTIFICATIONS: 'unread_all_notification',
  },
};
